impresso/impresso-middle-layer

src/hooks/params.js, src/models/newspapers.model.js, src/services/index.js, src/services/init/init.class.js, src/services/init/init.hooks.js, src/services/init/init.service.js, src/services/newspapers/newspapers.class.js, test/services/init.test.js
=> add init service to serve a preliminary list of stuff

src/hooks/search-info.js
Should fix #165 when no user info is shipped
=> get collection info only if a user has been specified

src/hooks/resolvers/mentions.resolvers.js, src/services/mentions/mentions.class.js, src/services/mentions/mentions.hooks.js
fix issue https://github.com/impresso/impresso-master-db/issues/51
=> fix performance, add "Faster" param to avoid sql COUNT

src/hooks/params.js, src/services/entities/entities.class.js, src/services/index.js, test/services/entities.test.js
should resolve frontend issue
https://github.com/impresso/impresso-frontend/issues/513
=> Fix entity id

package-lock.json, package.json
Should not affect anything else than the tests
=> update mocha to 6.x

src/services/entities/entities.class.js, src/services/mentions/mentions.hooks.js
Fix Frontend error: Entity page / Mentions: Error message #607 (Bad Request)
https://github.com/impresso/impresso-frontend/issues/607
=> Fix bad request on entities uids containing parenthesis

src/models/articles.model.js
=> workaround for articles without page_id_ss field

.github/workflows/docker-build-publish.yml
Build `latest` image from `develop` branch on every push.
=> docker hub build image

package-lock.json, package.json, src/cachedSolr.js, src/services/search-queries-comparison/index.d.ts, src/services/search-queries-comparison/schema/post/payload.json, src/services/search-queries-comparison/schema/post/response.json, src/services/search-queries-comparison/search-queries-comparison.class.js, src/services/search-queries-comparison/search-queries-comparison.hooks.js, test/services/search-queries-comparison.test.js, tsconfig.json
Required for https://github.com/impresso/impresso-frontend/pull/827
=> Compare queries endpoint

src/models/issues.model.js, src/services/users/users.hooks.js
Fix for https://github.com/impresso/impresso-frontend/issues/762
=> Check if cover is empty

src/services/articles-search/logic.js
For https://github.com/impresso/impresso-frontend/issues/853
=> Fixed misspelled field

scripts/loadtests/README.md, scripts/loadtests/articleSearch.js, scripts/loadtests/embeddings.js, scripts/loadtests/suggestions.js, src/app.hooks.js, src/cache.js, src/cachedSolr.js, src/httpConnectionPool.js, src/services/embeddings/embeddings.class.js, src/services/ngram-trends/ngram-trends.class.js, src/services/version/logic.js, src/solr.js
* added load tests
* replaced mutation with copy in solr client to get around an object reuse issue
* updated cache default TTL
* reduced default connection pool size and connection acquire timeout
=> Performance improvements

package-lock.json, package.json, scripts/import-articles.js, scripts/import-issues.js, scripts/update-facet-ranges.js, scripts/update-newspapers.js, scripts/update-topics-related.js, scripts/update-topics.js, scripts/update-years.js, src/services/search-exporter/search-exporter.class.js, src/solr.js, test/integration/solr.test.js
* Fixes solr issues in initialisation scripts.
=> Release 2.1.1

package-lock.json, package.json, scripts/update-facet-ranges.js, scripts/update-newspapers.js, scripts/update-topics-related.js, scripts/update-topics.js, scripts/update-years.js
* proper exit codes for `update_*` scripts.
=> Release 2.1.2

src/services/entities/entities.class.js, src/services/entities/entities.hooks.js, src/services/entities/logic.js, src/util/solr/filterReducers.js, src/util/solr/solrFilters.yml, test/util/solr/reducers.test.js
Slight refactoring of the entities search query.
=> Updated search query

src/data/constants.js, src/services/filters-items/filters-items.class.js
Enabled content length filter.
=> Content length filter

src/data/constants.js
Fix for https://github.com/impresso/impresso-frontend/issues/985 (backend part)
=> Daterange facet for search index

src/util/solr/filterReducers.js
Bug noticed in https://github.com/impresso/impresso-frontend/issues/985
=> Use filter operator if provided

src/services/filters-items/extractors.js, src/solr.js
Fix for https://github.com/impresso/impresso-frontend/issues/989
=> Use `post` request only for Solr and parse dates properly

src/data/constants.js, src/util/solr/solrFilters.yml
added collection facet/filter for tr_passages. Use tr_passages for cluster facets
=> Filter clusters by collections

src/util/solr/index.js, test/util/solr/reducers.test.js
Fixes https://github.com/impresso/impresso-frontend/issues/1258
=> [frontend issue/1258]fixed negation in complex query

package-lock.json, package.json, src/services/sequelize.service.js, src/services/wikidata.ts, src/util/serialize.ts, test/util/serialize.test.js
Also converted wikidata service to TS
Fixes https://github.com/impresso/impresso-frontend/issues/1275
=> Fixed entities caching issue

src/util/solr/filterReducers.js, test/util/solr/reducers.test.js
Fixes https://github.com/impresso/impresso-frontend/issues/1311
=> [issue-1311] remove parentheses

src/schema/schemas/ImpressoNerEntity.json
NER schema updated to match the latest NER data format.
=> updated ner schema

package.json, src/schema/schemas/ImpressoNerEntity.json
* Updated NER endpoint schema.
=> Release v3.0.1

src/schema/schemas/Article.json, src/schema/schemas/Newspaper.json, src/schema/schemas/SearchFacet.json, src/schema/schemas/SearchFacetBucket.json, src/schema/schemas/TextReusePassage.json, src/services/articles-search/schema/create/payload.json, src/services/entity-mentions-timeline/schema/create/payload.json
`$oneOf` (incorrect) -> `oneOf` (correct)
=> [chore] fixed schema definitions

src/schema/schemas/ImpressoNerEntity.json, src/services/impresso-ner/impresso-ner.class.ts
=> Release v3.0.6

src/authentication.ts, src/hooks/redaction.ts, src/util/serialize.ts
Fixes https://github.com/impresso/impresso-middle-layer/issues/472
=> treat missing bitmap as a guest

src/services/change-password/change-password.class.ts, src/services/change-password/change-password.service.ts, src/services/index.ts
=> create class and service, add basic password validation

src/hooks/redaction.ts, src/models/articles.model.js, src/models/images.model.js, src/models/text-reuse-passages.model.js, src/services/admin/admin.class.ts, src/services/articles/articles.hooks.js, src/services/articles/resources/contentItemRedactionPolicyWebApp.yml, src/services/images/images.hooks.js, src/services/images/images.service.js, src/services/images/resources/imageRedactionPolicyWebApp.yml, src/services/search-exporter/search-exporter.class.js, src/services/search/search.hooks.js, src/services/text-reuse-clusters/text-reuse-clusters.class.ts, src/services/text-reuse-clusters/text-reuse-clusters.hooks.js, src/services/text-reuse-passages/text-reuse-passages.hooks.js, src/useCases/getContentItemsPermissionsDetails.ts, src/util/bigint.ts, test/integration/use_cases/permissions.test.ts
Added more integration tests for permissions. Changes to the code where things were not working.
=> More permissions tests

src/services/topics-graph/topics-graph.class.js, src/util/solr/filterBuilders/value.ts, src/util/solr/filterReducers.ts, src/util/solr/index.ts, src/util/solr/solrFilters.yml, test/util/solr/reducers.test.ts
Fixes https://github.com/impresso/impresso-frontend/issues/418
=> Fixed escaping of entities ID values

src/services/embeddings/embeddings.class.js, src/util/solr/filterReducers.ts
Fixes https://github.com/impresso/impresso-middle-layer/issues/432
=> Escape ^ in embeddings

src/util/solr/filterBuilders/value.ts, test/util/solr/reducers.test.ts
Fixes https://github.com/impresso/impresso-frontend/issues/1452
=> Improved ID escape functions

src/services/search/search.hooks.js
Fixes https://github.com/impresso/impresso-middle-layer/issues/509
=> resolve topics in the search service

src/services/images/images-v1.hooks.ts
* fixed image search with v1 schema
=> Release v3.1.2

src/internalServices/cachedResolvers.ts, src/internalServices/facetResolvers/partnerResolver.ts
Fixes https://github.com/impresso/impresso-middle-layer/issues/502
=> added partner resolver

src/authentication.ts, src/models/users.model.ts
=> 196 update last login info in user table

src/util/solr/filterReducers.ts, test/hooks/search.test.js, test/util/solr/reducers.test.ts
Fixes https://github.com/impresso/impresso-middle-layer/issues/549
=> updated daterange filter parser and tests

package-lock.json, package.json, src/hooks/iiif.ts, src/middleware/imageProxy.ts, src/util/iiif.ts, test/util/iiif.test.ts, tsconfig.json
Fixes https://github.com/impresso/impresso-middle-layer/issues/532
=> Ensure IIIF URLs are v3 compatible before they are requested from downstream in image proxy

src/services/articles-suggestions/articles-suggestions.class.ts, src/services/articles-suggestions/articles-suggestions.service.js
Fixes https://github.com/impresso/impresso-frontend/issues/1544
=> Resolve entities

src/services/embeddings/embeddings.class.ts
Fixes https://github.com/impresso/impresso-frontend/issues/1556
=> search lowercase

src/hooks/resolvers.ts
Fixes https://github.com/impresso/impresso-middle-layer/issues/595
=> Requesting more items ahread because Solr cluster may return more items than IDs

src/data/constants.ts, src/util/solr/solrFilters.yml
https://github.com/impresso/impresso-frontend/issues/1744
=> added organisation facet to TR passages
